# Generated by Django 3.2 on 2022-02-23 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_tovar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sotrudnik',
            fields=[
                ('code_sotr', models.AutoField(db_column='SOTRUD_ID', help_text='Код сотрудника', primary_key=True, serialize=False, unique=True, verbose_name='Код сотрудника')),
                ('FIO', models.CharField(db_column='SOTRUD_FIO', help_text='ФИО сотрудника', max_length=255, verbose_name='ФИО сотрудника')),
                ('dolgnost', models.CharField(blank=True, db_column='SOTRUD_DOLG', help_text='Должность', max_length=255, null=True, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, db_column='SOTRUD_PHONE', help_text='Телефон', max_length=15, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудник',
                'db_table': 'SOTRUD',
            },
        ),
        migrations.CreateModel(
            name='Sotrudnik_Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.ForeignKey(db_column='CABINET_ID', on_delete=django.db.models.deletion.CASCADE, related_name='sotrudnik_cabinet', related_query_name='sotrudnik_cabinet', to='core.cabinet', verbose_name='Ссылка на кабинет')),
                ('sotrudnik', models.ForeignKey(db_column='SOTRUD_ID', on_delete=django.db.models.deletion.CASCADE, related_name='sotrudnik_cabinet', related_query_name='sotrudnik_cabinet', to='people.sotrudnik', verbose_name='Ссылка на сотрудника')),
            ],
            options={
                'verbose_name': 'Связка сотрудников с кабинетами',
                'verbose_name_plural': 'Связка сотрудников с кабинетами',
                'db_table': 'sotrudnik_cabinet',
            },
        ),
    ]
