# Generated by Django 3.2 on 2022-05-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20220512_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotrudnik',
            name='username',
            field=models.CharField(db_column='SOTRUD_FIO', help_text='Имя профиля', max_length=255, unique=True, verbose_name='Имя профиля'),
        ),
    ]
