# Generated by Django 3.2 on 2022-02-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id_cabinet', models.AutoField(db_column='CABINET_ID', help_text='Код кабинета', primary_key=True, serialize=False, unique=True, verbose_name='Код кабинета')),
                ('number_cabinet', models.CharField(db_column='CABINET_NUM', help_text='Номер кабинета', max_length=10, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинет',
                'db_table': 'CABINET',
            },
        ),
        migrations.CreateModel(
            name='Otdel',
            fields=[
                ('id_otdel', models.AutoField(db_column='OTDEL_ID', help_text='Код отдела', primary_key=True, serialize=False, unique=True, verbose_name='Код отдела')),
                ('naim_otdel', models.CharField(db_column='OTDEL_NAME', help_text='Наименование отдела', max_length=255, verbose_name='Наименование отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отдел',
                'db_table': 'OTDEL',
            },
        ),
        migrations.CreateModel(
            name='CabinetOtdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.ForeignKey(db_column='CABINET_ID', on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_otdel', related_query_name='cabinet_otdel', to='core.cabinet', verbose_name='Ссылка на кабинет')),
                ('otdel', models.ForeignKey(db_column='OTDEL_ID', on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_otdel', related_query_name='cabinet_otdel', to='core.otdel', verbose_name='Ссылка на отдел')),
            ],
            options={
                'verbose_name': 'Связка кабинетов с отделами',
                'verbose_name_plural': 'Связка кабинетов с отделами',
                'db_table': 'cabinet_otdel',
            },
        ),
    ]
