# Generated by Django 3.2 on 2022-02-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('code_tovar', models.AutoField(db_column='TOVAR_ID', help_text='Код товара', primary_key=True, serialize=False, unique=True, verbose_name='Код товара')),
                ('naim_tovar', models.CharField(db_column='TOVAR_NAIM', help_text='Наименование товара', max_length=255, verbose_name='Наименование товара')),
                ('kolvo_tovar', models.IntegerField(db_column='TOVAR_KOLVO', help_text='Количество товара', verbose_name='Количество товара')),
                ('cena_tovar', models.IntegerField(db_column='TOVAR_CENA', help_text='Цена за единицу', verbose_name='Цена за единицу')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
                'db_table': 'TOVAR',
            },
        ),
    ]
