version: '3.3'

services:
  db_borisova:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs
volumes:
  postgres_data: