# Generated by Django 3.2 on 2022-02-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka_Canc',
            fields=[
                ('id', models.AutoField(db_column='ZAYV_CANC_IZ', help_text='Номер заявки на канцелярию', primary_key=True, serialize=False, unique=True, verbose_name='Номер заявки на канцелярию')),
                ('date_zayvka', models.DateField(auto_now_add=True, db_column='ZAYV_CANC_DATE', help_text='Дата заявки на канцелярию', verbose_name='Дата заявки на канцелярию')),
                ('vid_zayavka', models.IntegerField(choices=[(0, 'Заявка создана'), (1, 'Заявка активна'), (2, 'Заявка закрыта')], db_column='ZAYV_CANC_VID', verbose_name='Вид заявки')),
                ('summa', models.DecimalField(blank=True, db_column='ZAYV_CANC_SUMMA', decimal_places=2, max_digits=10, null=True, verbose_name='Общая стоимость')),
            ],
            options={
                'verbose_name': 'Заявка на канцелярию',
                'verbose_name_plural': 'Заявка на канцелярию',
                'db_table': 'ZAYV_CANC',
            },
        ),
    ]
