# Generated by Django 3.2 on 2022-02-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka_Polomka',
            fields=[
                ('id', models.AutoField(db_column='ZAYV_POLOM_ID', help_text='Номер заявки о поломке', primary_key=True, serialize=False, unique=True, verbose_name='Номер заявки о поломке')),
                ('date_zayvka', models.DateField(auto_now_add=True, db_column='ZAYV_POLOM_DATE', help_text='Дата заявки о поломке', verbose_name='Дата заявки о поломке')),
                ('vid_zayavka', models.IntegerField(choices=[(0, 'Заявка создана'), (1, 'Заявка активна'), (2, 'Заявка закрыта')], db_column='ZAYV_POLOM_VID', verbose_name='Вид заявки')),
            ],
            options={
                'verbose_name': 'Заявка о поломке',
                'verbose_name_plural': 'Заявка о поломке',
                'db_table': 'ZAYV_POLOMC',
            },
        ),
        migrations.CreateModel(
            name='Zayavka_Trans',
            fields=[
                ('id', models.AutoField(db_column='ZAYV_TRANS_ID', help_text='Номер заявки на транспорт', primary_key=True, serialize=False, unique=True, verbose_name='Номер заявки на транспорт')),
                ('date_zayvka', models.DateField(auto_now_add=True, db_column='ZAYV_TRANS_DATE', help_text='Дата заявки на транспорт', verbose_name='Дата заявки на транспорт')),
                ('vid_zayavka', models.IntegerField(choices=[(0, 'Заявка создана'), (1, 'Заявка активна'), (2, 'Заявка закрыта')], db_column='ZAYV_TRANS_VID', verbose_name='Вид заявки')),
                ('date_otpr', models.DateField(blank=True, db_column='ZAYV_TRANS_DATEOTPR', help_text='Дата отправления', null=True, verbose_name='Дата отправления')),
                ('time_otpr', models.TimeField(blank=True, db_column='ZAYV_TRANS_TIMEOTPR', help_text='Время отправления', null=True, verbose_name='Время отправления')),
                ('killomentrs', models.IntegerField(blank=True, db_column='ZAYV_TRANS_KILLOM', null=True, verbose_name='Киллометраж')),
            ],
            options={
                'verbose_name': 'Заявка на транспорт',
                'verbose_name_plural': 'Заявка на транспорт',
                'db_table': 'ZAYV_TRANS',
            },
        ),
        migrations.AlterField(
            model_name='zayavka_canc',
            name='id',
            field=models.AutoField(db_column='ZAYV_CANC_ID', help_text='Номер заявки на канцелярию', primary_key=True, serialize=False, unique=True, verbose_name='Номер заявки на канцелярию'),
        ),
    ]
