# Generated by Django 3.2 on 2022-03-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('core', '0002_tovar'),
        ('documents', '0002_auto_20220219_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka_canc',
            name='ispolnitel',
            field=models.ForeignKey(db_column='ZAYV_CANC_ISPOLNITEL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ispolnitel', related_query_name='ispolnitel', to='people.sotrudnik', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='zayavka_canc',
            name='tovar',
            field=models.ForeignKey(db_column='ZAYV_CANC_TOVAR', default='', on_delete=django.db.models.deletion.CASCADE, related_name='tovar', related_query_name='tovar', to='core.tovar', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zayavka_canc',
            name='zayavitel',
            field=models.ForeignKey(db_column='ZAYV_CANC_ZAYAVITEL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zayavitel', related_query_name='zayavitel', to='people.sotrudnik', verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='zayavka_canc',
            name='vid_zayavka',
            field=models.IntegerField(choices=[(0, 'Активная'), (1, 'Завершена')], db_column='ZAYV_CANC_VID', verbose_name='Вид заявки'),
        ),
    ]
