# Generated by Django 3.2 on 2022-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20220329_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka_trans',
            name='address',
            field=models.CharField(blank=True, db_column='ZAYV_TRANS_ADRES', help_text='Адрес', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='zayavka_trans',
            name='punkt_nazn',
            field=models.CharField(blank=True, db_column='ZAYV_TRANS_PUNKT', help_text='Пункт назначения', max_length=255, null=True, verbose_name='Пункт назначения'),
        ),
    ]
