# Generated by Django 3.2 on 2022-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20220512_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka_polomka',
            name='vid_zayavka',
            field=models.IntegerField(choices=[(0, 'Активная'), (1, 'Завершена')], db_column='ZAYV_POLOM_VID', verbose_name='Вид заявки'),
        ),
        migrations.AlterField(
            model_name='zayavka_trans',
            name='vid_zayavka',
            field=models.IntegerField(choices=[(0, 'Активная'), (1, 'Завершена')], db_column='ZAYV_TRANS_VID', verbose_name='Вид заявки'),
        ),
    ]
